import nodemailer from "nodemailer";
import type { ReportRecord, RoutedAuthority } from "../types";

export interface NotifyResult {
  authorityId: string;
  sent: boolean;
  detail: string;
}

function emailEnabled(): boolean {
  return process.env.EMAIL_ENABLED === "true" && Boolean(process.env.SMTP_HOST);
}

function buildTransporter() {
  return nodemailer.createTransport({
    host: process.env.SMTP_HOST,
    port: Number(process.env.SMTP_PORT || 587),
    secure: false,
    auth:
      process.env.SMTP_USER && process.env.SMTP_PASS
        ? {
            user: process.env.SMTP_USER,
            pass: process.env.SMTP_PASS,
          }
        : undefined,
  });
}

export async function notifyAuthorities(
  report: ReportRecord,
  routed: RoutedAuthority[],
  photoUrl: string | null
): Promise<NotifyResult[]> {
  const results: NotifyResult[] = [];

  for (const item of routed) {
    const to = item.authority.email;
    if (!to) {
      results.push({
        authorityId: item.authority.id,
        sent: false,
        detail: "No email on file — contact details stored for manual outreach",
      });
      continue;
    }

    if (!emailEnabled()) {
      results.push({
        authorityId: item.authority.id,
        sent: false,
        detail: `Email disabled (would notify ${to}) — report queued with contact details`,
      });
      continue;
    }

    try {
      const transporter = buildTransporter();
      await transporter.sendMail({
        from: process.env.SMTP_FROM || "noreply@hazardreporter.local",
        to,
        subject: `[Hazard Reporter] ${report.hazard_type} at ${report.latitude.toFixed(5)}, ${report.longitude.toFixed(5)}`,
        text: [
          `A public hazard report has been routed to ${item.authority.name}.`,
          "",
          `Role: ${item.role}`,
          `Reason: ${item.reason}`,
          `Hazard: ${report.hazard_type}`,
          `Description: ${report.description || "(none)"}`,
          `Location: ${report.latitude}, ${report.longitude}`,
          `Locality: ${report.locality || "unknown"}`,
          `County: ${report.county || "unknown"}`,
          `State: ${report.state || "unknown"}`,
          `Report ID: ${report.id}`,
          photoUrl ? `Photo: ${photoUrl}` : "Photo: not attached",
          "",
          "This message was generated by Hazard Reporter. Contact details are provided for coordination; this is not an automated filing into your internal systems.",
        ].join("\n"),
      });
      results.push({
        authorityId: item.authority.id,
        sent: true,
        detail: `Notification email sent to ${to}`,
      });
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      results.push({
        authorityId: item.authority.id,
        sent: false,
        detail: `Email failed: ${message}`,
      });
    }
  }

  return results;
}
